CAUCA-9-1-1/survip-mobile

- package-lock.json
- package.json
- src/app/app.module.ts
- src/interfaces/inspection.interface.ts
- src/models/inspection-detail.ts
- src/pages/inspection-list/inspection-list.ts
- src/pages/intervention-course-detail/intervention-course-detail.html
- src/pages/intervention-course-detail/intervention-course-detail.module.ts
- src/pages/intervention-course-detail/intervention-course-detail.ts
- src/pages/intervention-course-lane/intervention-course-lane.html
- src/pages/intervention-course-lane/intervention-course-lane.ts
- src/pages/intervention-course/intervention-course.html
- src/pages/intervention-course/intervention-course.module.ts
- src/pages/intervention-course/intervention-course.ts
- src/pages/login/login.ts
- src/pipes/order-by/order-by.ts
- src/pipes/pipes.module.ts
- src/providers/Base/authentification.service.ts
- src/providers/Base/http.service.ts
- src/providers/inspection-controller/inspection-controller.ts
- src/providers/repositories/firestation-repository-provider.service.ts
- src/providers/repositories/inspection-building-course-lane-repository-provider.service.ts
- src/providers/repositories/inspection-building-course-repository.ts
- src/providers/repositories/route-direction-repository.ts
Je sais que la branche est mal nommée, j'avais pas vu que j'étais dans la mauvaise avant ce matin.
> #14 Course management

- src/app/app.scss
- src/components/menu-profile/menu-profile.html
- src/components/menu-profile/menu-profile.ts
- src/models/inspection-detail.ts
- src/models/inspection-visit.ts
- src/pages/inspection-list/inspection-list.html
- src/pages/inspection-question-summary/inspection-question-summary.ts
- src/pages/inspection-visit/inspection-visit.html
- src/pages/inspection-visit/inspection-visit.module.ts
- src/pages/inspection-visit/inspection-visit.scss
- src/pages/inspection-visit/inspection-visit.ts
- src/pages/intervention-general/intervention-general.html
- src/pages/intervention-general/intervention-general.scss
- src/pages/intervention-general/intervention-general.ts
- src/providers/Base/http.service.ts
- src/providers/repositories/inspection-detail-repository-provider.service.ts
Fonctions : 
- Commencer une inspection
- Refuser/annuler visite 
- Compléter une inspection
Le mode "lecture seule" n'est pas encore intégré car il est générale aux formulaires enfants de l'inspection
> #41 inspection first page

- src/components/search-list/search-list.html
- src/components/search-list/search-list.ts
- src/pages/hazardous-material-selection/hazardous-material-selection.html
- src/pages/hazardous-material-selection/hazardous-material-selection.ts
- src/providers/repositories/hazardous-material-repository.ts
- src/providers/repositories/lane-repository.ts
Lane and hazardous materials
Return 30 rows at start
Request on value changes with debounce of 500ms
Validation on case sensitive
> #11 optimize search

- src/pages/city-fire-hydrant/city-fire-hydrant.html
remove button and add item by clicking on it directly
> feat(#82) : change method of adding fire hydrant

- src/pages/building-alarm-panels/building-alarm-panels.html
- src/pages/building-alarm-panels/building-alarm-panels.ts
- src/pages/building-anomaly-detail/building-anomaly-detail.html
- src/pages/building-anomaly-detail/building-anomaly-detail.ts
- src/pages/building-contact-detail/building-contact-detail.html
- src/pages/building-contact-detail/building-contact-detail.ts
- src/pages/building-hazardous-material-detail/building-hazardous-material-detail.html
- src/pages/building-hazardous-material-detail/building-hazardous-material-detail.ts
- src/pages/building-pnap-detail/building-pnap-detail.html
- src/pages/building-pnap-detail/building-pnap-detail.ts
- src/pages/building-water-sprinklers/building-water-sprinklers.html
- src/pages/building-water-sprinklers/building-water-sprinklers.ts
- src/providers/Base/http.service.ts
Plusieurs pages avaient ce problème.
> Fix(#87) Footer blanc quand les boutons sont cachés.

- src/components/building-child-pictures/building-child-pictures.ts
Problem of index when deleting pictures when there is only one pictures
> feat(#47) : Hot fix on deleting pictures

- src/pages/inspection-list/inspection-list.html
- src/pages/inspection-list/inspection-list.scss
- src/pages/inspection-list/inspection-list.ts
Show message to user when there is no inspection to check.
> feat(#89) : Add message to user when there are no assigned inspection

- src/app/app.module.ts
- src/pages/building-main/building-main.ts
- src/pages/home/home.html
- src/pages/home/home.module.ts
- src/pages/home/home.ts
- src/pages/inspection-list/inspection-list.html
- src/pages/inspection-list/inspection-list.module.ts
- src/pages/inspection-list/inspection-list.ts
- src/pages/intervention-home/intervention-home.ts
- src/pages/login/login.ts
Add menu in inspection-list page to allow a logout and prepare futur options
> #84 inspection list navigation

- config.xml
- ionic.config.json
- src/providers/Base/http.service.ts
- src/providers/repositories/person-requiring-assistance-type-repository.ts
- src/providers/repositories/risk-level-repository.ts
- src/providers/repositories/utilisation-code-repository.ts
Modify PNAP, risk level, and utilisation code request to add localization routing.
> #95 localized mobile request

- src/pages/inspection-question/inspection-question.ts
- Add a reload of the inspection detail on the form laod(added in a previous issue)
-> triggered each time you use navigation by the inspection menu
- **Add reload of the inspection detail when leaving the survey if the previous page was the inspection detail**
-> the reload of the inspection will be triggered by the navigation menu in the other cases
> #51 inspection detail back reload

- src/assets/config/config.json
- src/providers/Base/http.service.ts
Add a general config to mobile to remove hard coded data from http service
> feat(#90) Add general config file for mobile app

- src/components/building-child-pictures/building-child-pictures.html
- src/components/building-child-pictures/building-child-pictures.ts
- src/components/inspection-building-particular-risk-detail/inspection-building-particular-risk-detail.ts
- src/components/picture-viewer/picture-viewer.html
- src/components/picture-viewer/picture-viewer.ts
- src/interfaces/building-child-picture-repository-provider.ts
- src/models/inspection-building-anomaly.ts
- src/models/inspection-building-child-picture-for-web.ts
- src/pages/building-anomaly-detail/building-anomaly-detail.html
- src/pages/building-anomaly-detail/building-anomaly-detail.ts
- src/pages/building-child-picture-edition/building-child-picture-edition.html
- src/pages/building-child-picture-edition/building-child-picture-edition.ts
- src/pages/intervention-general/intervention-general.html
- src/pages/intervention-general/intervention-general.ts
- src/providers/Base/http.service.ts
- src/providers/inspection-controller/inspection-controller.ts
- src/providers/repositories/inspection-building-anomaly-picture-repository-provider.service.ts
- src/providers/repositories/inspection-building-particular-risk-picture-repository-provider.service.ts
- src/providers/repositories/inspection-detail-repository-provider.service.ts
Faire l'API d'abord #96. 
- Ajout de validation sur le champs notes pour ne pas avoir de liste sans titre dans la liste des anomalies
> feat(#96) Validation on saving + refactoring

- src/pages/building-anomaly-detail/building-anomaly-detail.ts
- src/pages/intervention-general/intervention-general.ts
allow mobile to restart inpsection when refused or canceled
> #133 validate start inspection

- src/app/app.module.ts
Resolve probleme with keyboard and text-area.
> #144 survey problem text area

- src/pages/building-anomaly-detail/building-anomaly-detail.ts
Force form Value changes on adding picture to trigger the saving method
> #147 anomaly picture saving

- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/pages/intervention-general/intervention-general.html
- src/pages/intervention-general/intervention-general.ts
- src/pages/intervention-home/intervention-home.ts
- src/providers/inspection-configuration/inspection-configuration.ts
- src/providers/repositories/inspection-detail-repository-provider.service.ts
Add validation on user acces to inpsection menu:
- disable navigation menu if the inspection is not started or if the user doesn't have access
> #132 validation inspection edit mode

- package-lock.json
- package.json
Ne devrait strictement rien changer dans l'applicaiton mobile, mais facilite l'affichage du croquis enregistré dans l'application web
> feat(#285): Changed saving in SketchTool

- src/pages/inspection-survey-summary/inspection-survey-summary.module.ts
- src/pages/inspection-survey-summary/inspection-survey-summary.ts
- src/pages/intervention-general/intervention-general.ts
Corrige le problème d'Affichage du sommaire du questionnaire
Corrige le problème de page non trouvée du sommaire du questionnaire(#210 )
> #211 survey summary display

- config.xml
- package-lock.json
- package.json
- scripts/fix_android_hockeyapp_camera.js
- src/pages/version-validator/version-validator.ts
- src/providers/Base/authentification.service.ts
Correctif de la prise de photo sur android
Correctif de la validation de version et de communication serveur à l'ouverture de l'application
> #215 picture plugin problem

- src/components/pictures/pictures.component.html
- src/components/pictures/pictures.component.ts
- src/models/inspection-picture-for-web.ts
- src/pages/building-child-picture-edition/building-child-picture-edition.ts
- src/pages/intervention-implantation-plan-sketch/intervention-implantation-plan-sketch.ts
- src/providers/repositories/picture-repository.ts
Ne change absolument rien pour l'utilisation mobile, mais facilite permet le reload dans la version web.
> feat(#231): Forced saving of width and height

- src/components/components.module.ts
- src/components/custom-select/custom-select.html
- src/components/custom-select/custom-select.scss
- src/components/custom-select/custom-select.ts
- src/components/inspection-building-particular-risk-detail/inspection-building-particular-risk-detail.html
- src/components/inspection-building-particular-risk-detail/inspection-building-particular-risk-detail.ts
Need to create a new task to modify all select component that we could want to clear value through the mobile app by this one.
> feat(#239) Create select component with clear button

- config.xml
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/components/search-list/search-list.ts
- src/models/inspection-building-hazardous-material.ts
- src/pages/building-hazardous-material-detail/building-hazardous-material-detail.html
- src/pages/building-hazardous-material-detail/building-hazardous-material-detail.ts
- src/pages/hazardous-material-selection/hazardous-material-selection.ts
- src/pipes/order-by/order-by.ts
- src/providers/repositories/inspection-building-hazardous-material-repository.ts
Attention, aussi un pull request dans l'API.
> #236 hazardous materials

- src/app/app.component.ts
- src/app/app.scss
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/pages/city-fire-hydrant/city-fire-hydrant.html
- src/pages/city-fire-hydrant/city-fire-hydrant.ts
- src/pages/fire-hydrant/fire-hydrant.html
- src/pages/fire-hydrant/fire-hydrant.ts
- src/pages/intervention-water-supplies/intervention-water-supplies.html
Attention, pull request web-api va avec ça.
> #263 fire hydrants

- src/pages/inspection-list/inspection-list.ts
The loading freeze probleme has not neen fixed but i put some optimization in loading process,
> #238 error on delay activity

- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/components/pictures/pictures.component.ts
- src/interfaces/pictures-repository-provider.interface.ts
- src/models/inspection-configuration.ts
- src/pages/building-child-picture-edition/building-child-picture-edition.ts
- src/pages/intervention-implantation-plan/intervention-implantation-plan.ts
- src/providers/Base/http.service.ts
- src/providers/repositories/inspection-building-anomaly-picture-repository-provider.service.ts
- src/providers/repositories/inspection-building-particular-risk-picture-repository-provider.service.ts
- src/providers/repositories/picture-repository.ts
Check the web-api pull request first(#231)
> #283 picture format and save

- package.json
Empêche la sélection de plusieurs modes simultanément.
> feat(#282) updated sketch tool to prevent multiple selection

- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/interfaces/inspection.interface.ts
- src/pages/building-details/building-details.html
- src/pages/building-details/building-details.ts
- src/pages/intervention-buildings/intervention-buildings.html
- src/pages/intervention-buildings/intervention-buildings.ts
- src/pages/intervention-general/intervention-general.html
- src/providers/inspection-controller/inspection-controller.ts
Attention, attention!  
Les changements à corporateName et à aliasName ne sont pas sauvegardés quand on upload l'inspection complété.  Je vais faire cette partie dans l'autre point qui est d'ajouté le champ "corporateName" au bâtiment.   Tout le reste devrait fonctionner.
> #318 corporate name and alias edition

- src/app/core/services/authentication/authentification.service.ts
- src/app/inspection/components/survey-parent-child-question/survey-parent-child-question.component.html
- src/app/inspection/components/survey-parent-child-question/survey-parent-child-question.component.ts
- src/app/inspection/components/survey-question/survey-question.component.ts
- src/app/inspection/inspection-survey/inspection-survey.component.html
- src/app/inspection/inspection-survey/inspection-survey.component.ts
Modify minimum occurrence navigation validation
Add display validation on grouped question type
> feat(#338): Fix mobile survey navigation
